// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace IPInfoWebAPI.Models
{
    public partial class IpInformationsContext : DbContext
    {
        public IpInformationsContext()
        {
        }

        public IpInformationsContext(DbContextOptions<IpInformationsContext> options)
            : base(options)
        {
        }

        public virtual DbSet<IpDetail> Ipdetails { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<IpDetail>(entity =>
            {
                entity.HasKey(e => e.Ip)
                    .HasName("PK__IPDetail__3214EC2B3DCC555C");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}